export enum BarcodeScannerAppState {
  INITIAL = 'INITIAL',
  DEFAULT = 'DEFAULT',
  SCANNING = 'SCANNING',
  SCANNED = 'SCANNED',
  INPUT_ID = 'INPUT_ID',
  INPUT_INITIALS = 'INPUT_INITIALS',
  INPUT_LINE_COUNT = 'INPUT_LINE_COUNT',
  PRINTING = 'PRINTING',
  SYNC = 'SYNC',
  ERROR = 'ERROR',
  SETTINGS = 'SETTINGS',
}
