export enum BarcodeScannerAppState {
  INITIAL = 'INITIAL',
  DEFAULT = 'DEFAULT',
  SCANNING = 'SCANNING',
  SCANNED = 'SCANNED',
  INPUT = 'INPUT',
  PRINTING = 'PRINTING',
  PRINTED = 'PRINTED',
  ERROR = 'ERROR',
  SETTINGS = 'SETTINGS',
}
